spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/two_tables_database?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true